-- begin PLATFORM_EMPLOYEE_COURSE
alter table PLATFORM_EMPLOYEE_COURSE add constraint FK_PLATFORM_EMPLOYEE_COURSE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references PLATFORM_EMPLOYEE(ID)^
alter table PLATFORM_EMPLOYEE_COURSE add constraint FK_PLATFORM_EMPLOYEE_COURSE_ON_COURSE foreign key (COURSE_ID) references PLATFORM_COURSE(ID)^
create index IDX_PLATFORM_EMPLOYEE_COURSE_ON_EMPLOYEE on PLATFORM_EMPLOYEE_COURSE (EMPLOYEE_ID)^
create index IDX_PLATFORM_EMPLOYEE_COURSE_ON_COURSE on PLATFORM_EMPLOYEE_COURSE (COURSE_ID)^
-- end PLATFORM_EMPLOYEE_COURSE
-- begin PLATFORM_COURSE
alter table PLATFORM_COURSE add constraint FK_PLATFORM_COURSE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references PLATFORM_EMPLOYEE(ID)^
create index IDX_PLATFORM_COURSE_ON_EMPLOYEE on PLATFORM_COURSE (EMPLOYEE_ID)^
-- end PLATFORM_COURSE
-- begin PLATFORM_EMPLOYEE
alter table PLATFORM_EMPLOYEE add constraint FK_PLATFORM_EMPLOYEE_ON_POSITION foreign key (POSITION_ID) references PLATFORM_POSITION(ID)^
create index IDX_PLATFORM_EMPLOYEE_ON_POSITION on PLATFORM_EMPLOYEE (POSITION_ID)^
-- end PLATFORM_EMPLOYEE
-- begin PLATFORM_CHAPTER
alter table PLATFORM_CHAPTER add constraint FK_PLATFORM_CHAPTER_ON_COURSE foreign key (COURSE_ID) references PLATFORM_COURSE(ID)^
create index IDX_PLATFORM_CHAPTER_ON_COURSE on PLATFORM_CHAPTER (COURSE_ID)^
-- end PLATFORM_CHAPTER
-- begin PLATFORM_QUESTION
alter table PLATFORM_QUESTION add constraint FK_PLATFORM_QUESTION_ON_CHAPTER foreign key (CHAPTER_ID) references PLATFORM_CHAPTER(ID)^
create index IDX_PLATFORM_QUESTION_ON_CHAPTER on PLATFORM_QUESTION (CHAPTER_ID)^
-- end PLATFORM_QUESTION
-- begin PLATFORM_EMPLOYEE_CHAPTER
alter table PLATFORM_EMPLOYEE_CHAPTER add constraint FK_PLATFORM_EMPLOYEE_CHAPTER_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references PLATFORM_EMPLOYEE(ID)^
alter table PLATFORM_EMPLOYEE_CHAPTER add constraint FK_PLATFORM_EMPLOYEE_CHAPTER_ON_CHAPTER foreign key (CHAPTER_ID) references PLATFORM_CHAPTER(ID)^
create index IDX_PLATFORM_EMPLOYEE_CHAPTER_ON_EMPLOYEE on PLATFORM_EMPLOYEE_CHAPTER (EMPLOYEE_ID)^
create index IDX_PLATFORM_EMPLOYEE_CHAPTER_ON_CHAPTER on PLATFORM_EMPLOYEE_CHAPTER (CHAPTER_ID)^
-- end PLATFORM_EMPLOYEE_CHAPTER
