alter table PLATFORM_EMPLOYEE add constraint FK_PLATFORM_EMPLOYEE_ON_POSITION foreign key (POSITION_ID) references PLATFORM_POSITION(ID);
create index IDX_PLATFORM_EMPLOYEE_ON_POSITION on PLATFORM_EMPLOYEE (POSITION_ID);
