alter table PLATFORM_CHAPTER add constraint FK_PLATFORM_CHAPTER_ON_COURSE foreign key (COURSE_ID) references PLATFORM_COURSE(ID);
create index IDX_PLATFORM_CHAPTER_ON_COURSE on PLATFORM_CHAPTER (COURSE_ID);
