alter table PLATFORM_EMPLOYEE_COURSE add constraint FK_PLATFORM_EMPLOYEE_COURSE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references PLATFORM_EMPLOYEE(ID);
alter table PLATFORM_EMPLOYEE_COURSE add constraint FK_PLATFORM_EMPLOYEE_COURSE_ON_COURSE foreign key (COURSE_ID) references PLATFORM_COURSE(ID);
create index IDX_PLATFORM_EMPLOYEE_COURSE_ON_EMPLOYEE on PLATFORM_EMPLOYEE_COURSE (EMPLOYEE_ID);
create index IDX_PLATFORM_EMPLOYEE_COURSE_ON_COURSE on PLATFORM_EMPLOYEE_COURSE (COURSE_ID);
