alter table PLATFORM_QUESTION add constraint FK_PLATFORM_QUESTION_ON_CHAPTER foreign key (CHAPTER_ID) references PLATFORM_CHAPTER(ID);
create index IDX_PLATFORM_QUESTION_ON_CHAPTER on PLATFORM_QUESTION (CHAPTER_ID);
