alter table PLATFORM_COURSE add constraint FK_PLATFORM_COURSE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references PLATFORM_EMPLOYEE(ID);
create index IDX_PLATFORM_COURSE_ON_EMPLOYEE on PLATFORM_COURSE (EMPLOYEE_ID);
